# Default dotfiles selections.

EXTERNAL_MODULE_REPOS=(
    # "myexternalmodule=atzufuki/myexternalmodule"
)

ACTIVE_MODULES=(
    # myexternalmodule
)

ACTIVE_SCRIPTS=(
    am
    deno
    gh
    llama-cpp
    opencode
    rust
    scarlett
    ssh
    telegram
    whatsapp
    zed
)
