#!/usr/bin/env bash

# Dotfiles command script.
# This script manages scripts and dotfile symlinks.

usage() {
    cat <<'EOF'
Usage: dotfiles <command>

Commands:
  configure  Select features and write dotfiles.conf
  apply      Apply dotfiles.conf and symlink dotfiles
  purge      Remove all dotfiles-managed changes and local config
  dry-run    Preview apply actions without changing files
  status     Check config, symlinks, scripts, and services
  help       Show this help

Short command:
  dot        Same as dotfiles when installed through setup.sh
EOF
}

if [[ $# -gt 1 ]]; then
    usage
    exit 1
fi

command="${1:-help}"
source_path="${BASH_SOURCE[0]}"
while [[ -L "$source_path" ]]; do
    source_dir="$(cd "$(dirname "$source_path")" && pwd)"
    source_path="$(readlink "$source_path")"
    [[ "$source_path" == /* ]] || source_path="$source_dir/$source_path"
done
script_dir="$(cd "$(dirname "$source_path")" && pwd)"
repo_dir="$script_dir"
ignore_file="$repo_dir/.dotfilesignore"
scripts_dir="$repo_dir/scripts"
defaults_file="$repo_dir/dotfiles.defaults.conf"
config_file="$repo_dir/dotfiles.conf"

case "$command" in
    configure)
        echo "[INFO] Configuring dotfiles."
        ;;
    apply)
        echo "[INFO] Applying dotfiles."
        ;;
    purge)
        echo "[INFO] Purging dotfiles."
        ;;
    dry-run)
        echo "[INFO] Previewing dotfiles apply."
        ;;
    status)
        echo "[INFO] Checking dotfiles status."
        ;;
    help|--help|-h)
        usage
        exit 0
        ;;
    *)
        usage
        exit 1
        ;;
esac

if [[ ! -d "$repo_dir" ]]; then
    echo "[ERROR] Dotfiles repo not found: $repo_dir"
    exit 1
fi

if [[ ! -f "$ignore_file" ]]; then
    echo "[ERROR] Ignore file not found: $ignore_file"
    exit 1
fi

if [[ ! -f "$defaults_file" ]]; then
    echo "[ERROR] Defaults file not found: $defaults_file"
    exit 1
fi

echo "[INFO] Found .dotfilesignore, processing files..."
cd "$repo_dir" || exit 1

list_contains() {
    local needle="$1"
    shift
    local item

    for item in "$@"; do
        [[ "$item" == "$needle" ]] && return 0
    done

    return 1
}

load_config() {
    source "$defaults_file"

    if [[ -f "$config_file" ]]; then
        # dotfiles.conf is generated by this tool and contains simple KEY=true/false values.
        source "$config_file"
    fi
}

ensure_config() {
    if [[ -f "$config_file" ]]; then
        return 0
    fi

    echo "[INFO] Creating local config: $config_file"
    cp "$defaults_file" "$config_file"
    configure_dotfiles
}

write_config() {
    local tmp_file="$config_file.tmp"
    local name

    {
        echo "# Local dotfiles selections. Generated by: dot configure"
        echo
        echo "ACTIVE_MODULES=("
        for name in "${ACTIVE_MODULES[@]}"; do
            printf '    %q\n' "$name"
        done
        echo ")"
        echo
        echo "ACTIVE_SCRIPTS=("
        for name in "${ACTIVE_SCRIPTS[@]}"; do
            printf '    %q\n' "$name"
        done
        echo ")"
    } > "$tmp_file"

    mv "$tmp_file" "$config_file"
}

prompt_bool() {
    local label="$1"
    local current="$2"
    local answer
    local suffix

    if [[ "$current" == "true" ]]; then
        suffix="Y/n"
    else
        suffix="y/N"
    fi

    while true; do
        if ! read -r -p "$label [$suffix]: " answer; then
            answer=""
        fi
        answer="${answer//[[:space:]]/}"
        case "$answer" in
            "") [[ "$current" == "true" ]] && return 0 || return 1 ;;
            y|Y|yes|YES) return 0 ;;
            n|N|no|NO) return 1 ;;
            *) echo "Please answer y or n." ;;
        esac
    done
}

configure_dotfiles() {
    local name
    local current
    local -a next_active_modules=()
    local -a next_active_scripts=()

    load_config

    echo "[INFO] Select modules."
    for name in $(available_modules); do
        if list_contains "$name" "${ACTIVE_MODULES[@]}"; then
            current=true
        else
            current=false
        fi

        if prompt_bool "Enable module $name" "$current"; then
            next_active_modules+=("$name")
        fi
    done

    echo "[INFO] Select scripts."
    for name in $(available_scripts); do
        if list_contains "$name" "${ACTIVE_SCRIPTS[@]}"; then
            current=true
        else
            current=false
        fi

        if prompt_bool "Enable script $name" "$current"; then
            next_active_scripts+=("$name")
        fi
    done

    ACTIVE_MODULES=("${next_active_modules[@]}")
    ACTIVE_SCRIPTS=("${next_active_scripts[@]}")

    write_config
    echo "[INFO] Wrote $config_file"
}

available_scripts() {
    local script

    shopt -s nullglob
    for script in "$scripts_dir"/*.sh; do
        basename "$script" .sh
    done
    shopt -u nullglob
}

script_dependencies() {
    local script_name="$1"
    local script="$scripts_dir/$script_name.sh"
    local line
    local deps
    local dep

    [[ -f "$script" ]] || return 0

    while IFS= read -r line; do
        [[ "$line" == "# dotfiles-depends:"* ]] || continue
        deps="${line#\# dotfiles-depends:}"
        for dep in $deps; do
            [[ -n "$dep" ]] && echo "$dep"
        done
    done < "$script"
}

reverse_items() {
    local -a items=("$@")
    local index

    for ((index = ${#items[@]} - 1; index >= 0; index--)); do
        echo "${items[$index]}"
    done
}

order_script_visit() {
    local script_name="$1"
    local dep

    case "${script_visit_state[$script_name]:-}" in
        visiting)
            echo "[ERROR] Circular script dependency detected at script: $script_name"
            exit 1
            ;;
        visited)
            return 0
            ;;
    esac

    if [[ ! -f "$scripts_dir/$script_name.sh" ]]; then
        echo "[ERROR] Script dependency is missing: $script_name"
        exit 1
    fi

    script_visit_state[$script_name]="visiting"
    while IFS= read -r dep; do
        [[ -n "$dep" ]] || continue
        if ! [[ -f "$scripts_dir/$dep.sh" ]]; then
            if [[ "$script_dependency_strict" == "true" ]]; then
                echo "[ERROR] Script $script_name depends on missing script $dep."
                exit 1
            fi
            continue
        fi

        if ! list_contains "$dep" "${script_order_scope[@]}"; then
            if [[ "$script_dependency_strict" == "true" ]]; then
                echo "[ERROR] Active script $script_name depends on inactive script $dep."
                exit 1
            fi
            continue
        fi

        order_script_visit "$dep"
    done < <(script_dependencies "$script_name")

    script_visit_state[$script_name]="visited"
    ordered_scripts+=("$script_name")
}

order_scripts() {
    local strict="$1"
    local script_name
    shift

    declare -g -a ordered_scripts
    declare -g -a script_order_scope
    declare -g -A script_visit_state
    declare -g script_dependency_strict

    ordered_scripts=()
    script_order_scope=("$@")
    script_dependency_strict="$strict"
    script_visit_state=()

    for script_name in "$@"; do
        order_script_visit "$script_name"
    done
}

available_modules() {
    local module_dir
    local entry
    local name

    shopt -s nullglob
    for module_dir in "$repo_dir"/modules/*; do
        [[ -d "$module_dir" ]] || continue
        basename "$module_dir"
    done
    shopt -u nullglob

    for entry in "${EXTERNAL_MODULE_REPOS[@]}"; do
        name="${entry%%=*}"
        [[ -n "$name" ]] && echo "$name"
    done | sort -u
}

managed_files() {
    local item

    while IFS= read -r item; do
        [[ "$item" == ".dotfilesignore" ]] && continue
        is_ignored_file "$item" && continue
        echo "$item"
    done < <(find . -type f | sed 's|^./||')
}

is_ignored_file() {
    local item="$1"
    local pattern

    while IFS= read -r pattern; do
        [[ -z "$pattern" || "$pattern" == \#* ]] && continue
        if [[ "$pattern" == *"*"* || "$pattern" == *"?"* || "$pattern" == *"["* ]]; then
            [[ "$item" == $pattern ]] && return 0
        elif [[ "$pattern" == */ ]]; then
            [[ "$item" == "$pattern"* ]] && return 0
        elif [[ "$item" == "$pattern" ]]; then
            return 0
        fi
    done < "$ignore_file"

    return 1
}

target_for() {
    echo "/$1"
}

skel_name_for() {
    case "$1" in
        home/atzufuki/.bashrc)
            echo ".bashrc"
            ;;
        home/atzufuki/.bash_profile)
            echo ".bash_profile"
            ;;
        *)
            return 1
            ;;
    esac
}

skel_source_for() {
    local skel_name="$1"

    if [[ -f "/usr/etc/skel/$skel_name" ]]; then
        echo "/usr/etc/skel/$skel_name"
    elif [[ -f "/etc/skel/$skel_name" ]]; then
        echo "/etc/skel/$skel_name"
    else
        return 1
    fi
}

is_repo_symlink() {
    local item="$1"
    local target="$2"
    local expected

    [[ -L "$target" ]] || return 1
    expected="$(readlink -f "$repo_dir/$item")"
    [[ "$(readlink -f "$target")" == "$expected" ]]
}

restore_skel_file() {
    local item="$1"
    local target="$2"
    local skel_name
    local skel_source

    skel_name="$(skel_name_for "$item")" || return 0
    skel_source="$(skel_source_for "$skel_name")" || {
        echo "[WARN] No skel restore source found for $target"
        return 0
    }

    if [[ -e "$target" && ! -L "$target" ]]; then
        echo "[INFO] Not restoring skel over existing regular file: $target"
        return 0
    fi

    mkdir -p "$(dirname "$target")"
    echo "[INFO] Restoring $target from $skel_source"
    cp "$skel_source" "$target"
}

print_skel_status() {
    local item="$1"
    local target="$2"
    local skel_name
    local skel_source

    skel_name="$(skel_name_for "$item")" || return 0
    if skel_source="$(skel_source_for "$skel_name")"; then
        echo "[SKEL] purge restore source for $target: $skel_source"
    else
        echo "[SKEL] purge restore source missing for $target"
    fi
}

legacy_removed_files() {
    echo "home/atzufuki/.profile"
}

cleanup_legacy_removed_files() {
    local action="$1"
    local item
    local target
    local expected
    local actual
    local raw_target

    while read -r item; do
        target="$(target_for "$item")"
        expected="$(readlink -f "$(dirname "$repo_dir/$item")")/$(basename "$item")"

        if [[ -L "$target" ]]; then
            raw_target="$(readlink "$target")"
            actual="$(readlink -f "$(dirname "$raw_target")")/$(basename "$raw_target")"
        else
            actual=""
        fi

        if [[ -L "$target" && "$actual" == "$expected" ]]; then
            case "$action" in
                apply|purge)
                    echo "[INFO] Removing legacy symlink: $target"
                    rm "$target"
                    ;;
                dry-run)
                    echo "[DRY-RUN] Would remove legacy symlink: $target"
                    ;;
                status)
                    echo "[LEGACY] $target is still linked to removed dotfile $repo_dir/$item"
                    ;;
            esac
        fi
    done < <(legacy_removed_files)
}

run_scripts() {
    local script_command="$1"
    local script
    local script_name
    local action
    local -a all_scripts=()
    local -a active_scripts=()
    local -a inactive_scripts=()
    local -a ordered_active_scripts=()
    local -a ordered_inactive_scripts=()
    local -a ordered_all_scripts=()

    if [[ ! -d "$scripts_dir" ]]; then
        return 0
    fi

    shopt -s nullglob
    for script in "$scripts_dir"/*.sh; do
        script_name="$(basename "$script" .sh)"
        all_scripts+=("$script_name")
        if list_contains "$script_name" "${ACTIVE_SCRIPTS[@]}"; then
            active_scripts+=("$script_name")
        else
            inactive_scripts+=("$script_name")
        fi
    done
    shopt -u nullglob

    if [[ ${#all_scripts[@]} -eq 0 ]]; then
        return 0
    fi

    echo "[INFO] Running scripts..."
    case "$script_command" in
        apply)
            order_scripts true "${active_scripts[@]}"
            ordered_active_scripts=("${ordered_scripts[@]}")

            for script_name in "${ordered_active_scripts[@]}"; do
                script="$scripts_dir/$script_name.sh"
                echo "[INFO] Running script: $script apply"
                DOTFILES_REPO_DIR="$repo_dir" bash "$script" apply || exit 1
            done
            ;;
        dry-run)
            order_scripts true "${active_scripts[@]}"
            ordered_active_scripts=("${ordered_scripts[@]}")

            for script_name in "${ordered_active_scripts[@]}"; do
                script="$scripts_dir/$script_name.sh"
                echo "[INFO] Running script: $script dry-run"
                DOTFILES_REPO_DIR="$repo_dir" bash "$script" dry-run || exit 1
            done
            ;;
        purge)
            order_scripts true "${active_scripts[@]}"
            ordered_active_scripts=("${ordered_scripts[@]}")
            mapfile -t ordered_active_scripts < <(reverse_items "${ordered_active_scripts[@]}")

            for script_name in "${ordered_active_scripts[@]}"; do
                script="$scripts_dir/$script_name.sh"
                echo "[INFO] Running script: $script purge"
                DOTFILES_REPO_DIR="$repo_dir" bash "$script" purge || exit 1
            done
            ;;
        status)
            order_scripts true "${all_scripts[@]}"
            ordered_all_scripts=("${ordered_scripts[@]}")

            for script_name in "${ordered_all_scripts[@]}"; do
                script="$scripts_dir/$script_name.sh"
                echo "[INFO] Running script: $script status"
                DOTFILES_REPO_DIR="$repo_dir" bash "$script" status || exit 1
            done
            ;;
        *)
            echo "[ERROR] Unsupported script command: $script_command"
            exit 1
            ;;
    esac
}

print_link_status() {
    local item="$1"
    local target
    local expected
    target="$(target_for "$item")"
    expected="$(readlink -f "$repo_dir/$item")"

    if [[ -L "$target" ]]; then
        if [[ "$(readlink -f "$target")" == "$expected" ]]; then
            echo "[OK] $target -> $repo_dir/$item"
            print_skel_status "$item" "$target"
        else
            echo "[CONFLICT] $target points to $(readlink "$target")"
        fi
    elif [[ -e "$target" ]]; then
        if skel_name="$(skel_name_for "$item")" && skel_source="$(skel_source_for "$skel_name")" && cmp -s "$target" "$skel_source"; then
            echo "[SKEL DEFAULT] $target exists as distro default and can be linked on apply"
            print_skel_status "$item" "$target"
        else
            echo "[CONFLICT] $target exists and is not a symlink"
        fi
    else
        echo "[MISSING] $target"
        print_skel_status "$item" "$target"
    fi
}

preview_link() {
    local item="$1"
    local target
    local expected
    target="$(target_for "$item")"
    expected="$(readlink -f "$repo_dir/$item")"

    if [[ -L "$target" && "$(readlink -f "$target")" == "$expected" ]]; then
        echo "[DRY-RUN] Would skip existing symlink: $target"
    elif [[ -e "$target" && ! -L "$target" ]]; then
        if skel_name="$(skel_name_for "$item")" && skel_source="$(skel_source_for "$skel_name")" && cmp -s "$target" "$skel_source"; then
            echo "[DRY-RUN] Would replace skel default with symlink: $target -> $repo_dir/$item"
        else
            echo "[DRY-RUN] Would conflict with existing file: $target"
        fi
    else
        echo "[DRY-RUN] Would create symlink: $target -> $repo_dir/$item"
    fi

    if skel_name_for "$item" >/dev/null; then
        local skel_name
        local skel_source
        skel_name="$(skel_name_for "$item")"
        if skel_source="$(skel_source_for "$skel_name")"; then
            echo "[DRY-RUN] On purge would restore $target from $skel_source"
        else
            echo "[DRY-RUN] On purge no skel restore source found for $target"
        fi
    fi
}

if [[ "$command" == "configure" ]]; then
    [[ -f "$config_file" ]] || cp "$defaults_file" "$config_file"
    configure_dotfiles
    exit 0
fi

if [[ "$command" == "apply" ]]; then
    ensure_config
fi

load_config

if [[ "$command" != "apply" ]]; then
    run_scripts "$command"
fi
cleanup_legacy_removed_files "$command"

if [[ "$command" == "status" ]]; then
    if [[ -f "$config_file" ]]; then
        echo "[INFO] Local config: $config_file"
    else
        echo "[INFO] Local config missing, using defaults: $defaults_file"
    fi

    while read -r item; do
        print_link_status "$item"
    done < <(managed_files)
    exit 0
fi

if [[ "$command" == "dry-run" ]]; then
    while read -r item; do
        preview_link "$item"
    done < <(managed_files)
    exit 0
fi

managed_files | while read -r item; do
    target="$(target_for "$item")"
    if [[ "$command" == "purge" ]]; then
        if is_repo_symlink "$item" "$target"; then
            echo "[INFO] Deleting symlink: $target"
            rm "$target"
            restore_skel_file "$item" "$target"
        elif [[ -L "$target" ]]; then
            echo "[INFO] Not deleting non-dotfiles symlink: $target"
        fi
    else
        if [[ -e "$target" && ! -L "$target" ]]; then
            if skel_name="$(skel_name_for "$item")" && skel_source="$(skel_source_for "$skel_name")" && cmp -s "$target" "$skel_source"; then
                echo "[INFO] Replacing skel default with symlink: $target"
            else
                echo "[WARN] Skipping existing regular file: $target"
                continue
            fi
        fi

        # Ensure parent directory exists.
        sudo mkdir -p "$(dirname "$target")"
        echo "[INFO] Creating symlink: $target -> $repo_dir/$item"
        sudo ln -sfn "$repo_dir/$item" "$target"
    fi
done

echo "[INFO] Reloading user systemd state..."
systemctl --user daemon-reload

if [[ "$command" == "apply" ]]; then
    run_scripts "$command"
elif [[ "$command" == "purge" ]]; then
    if [[ -f "$config_file" ]]; then
        echo "[INFO] Removing local config: $config_file"
        rm "$config_file"
    fi
fi

echo "[INFO] Dotfiles command complete!"
