# Default dotfiles selections.

EXTERNAL_MODULE_REPOS=(
    "dotprivate=atzufuki/dotprivate"
    # "myexternalmodule=atzufuki/myexternalmodule"
)

ACTIVE_MODULES=(
    # myexternalmodule
)

ACTIVE_SCRIPTS=(
    am
    antigravity-cli
    chrome
    deno
    gcm
    gcloud
    gh
    gnome-rounded-corners
    opencode
    slack
    ssh
    tailscale
    zed
)
