# Default dotfiles selections.

EXTERNAL_MODULE_REPOS=(
    # "myexternalmodule=atzufuki/myexternalmodule"
)

ACTIVE_MODULES=(
    # myexternalmodule
)

ACTIVE_SCRIPTS=(
    gh
    opencode
    scarlett
    zed
)
