#!/usr/bin/env bash

set -euo pipefail

command="${1:-apply}"
runtime_dir="${LLAMA_CPP_RUNTIME_DIR:-$HOME/.local/opt/llama.cpp}"
bin_dir="$HOME/.local/bin"
config_dir="$HOME/.config/llama.cpp"
models_dir="$HOME/.local/share/llama.cpp/models"
env_file="$config_dir/server.env"
start_script="$bin_dir/llama-cpp-server-start"
server_link="$bin_dir/llama-server"
service="llama-cpp.service"
repo_dir="${DOTFILES_REPO_DIR:-$HOME/.dotfiles}"
service_source="$repo_dir/home/atzufuki/.config/systemd/user/$service"
service_target="$HOME/.config/systemd/user/$service"

missing_commands() {
    local cmd
    local missing=0

    for cmd in curl tar; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            echo "[MISSING] Required command not found: $cmd"
            missing=1
        fi
    done

    return "$missing"
}

latest_release_tag() {
    curl -fsSL https://api.github.com/repos/ggml-org/llama.cpp/releases/latest |
        sed -n 's/.*"tag_name": "\([^"]*\)".*/\1/p' |
        head -n 1
}

asset_platform() {
    case "$(uname -m)" in
        x86_64)
            echo "ubuntu-vulkan-x64"
            ;;
        aarch64|arm64)
            echo "ubuntu-vulkan-arm64"
            ;;
        *)
            echo "[ERROR] Unsupported architecture for llama.cpp release binary: $(uname -m)" >&2
            return 1
            ;;
    esac
}

server_binary() {
    local candidate
    local -a candidates=()

    shopt -s nullglob globstar
    candidates=("$runtime_dir"/**/llama-server)
    shopt -u nullglob globstar

    for candidate in "${candidates[@]}"; do
        [[ -x "$candidate" ]] || continue
        echo "$candidate"
        return 0
    done

    return 1
}

install_release_binary() {
    local tag
    local platform
    local asset_name
    local download_url
    local tmp_dir
    local binary

    tag="$(latest_release_tag)"
    if [[ -z "$tag" ]]; then
        echo "[ERROR] Could not resolve latest llama.cpp release tag."
        exit 1
    fi

    platform="$(asset_platform)"
    asset_name="llama-${tag}-bin-${platform}.tar.gz"
    download_url="https://github.com/ggml-org/llama.cpp/releases/download/${tag}/${asset_name}"

    if [[ -f "$runtime_dir/VERSION" && "$(<"$runtime_dir/VERSION")" == "$tag" ]] && binary="$(server_binary)"; then
        echo "[INFO] llama.cpp release already installed: $tag"
        ln -sfn "$binary" "$server_link"
        return 0
    fi

    tmp_dir="$(mktemp -d)"
    trap 'rm -rf "$tmp_dir"' RETURN

    echo "[INFO] Downloading llama.cpp release binary: $asset_name"
    curl -fL "$download_url" -o "$tmp_dir/$asset_name"

    rm -rf "$runtime_dir"
    mkdir -p "$runtime_dir"
    tar -xzf "$tmp_dir/$asset_name" -C "$runtime_dir"

    binary="$(server_binary)" || {
        echo "[ERROR] llama-server binary was not found in release archive."
        exit 1
    }

    chmod +x "$binary"
    echo "$tag" > "$runtime_dir/VERSION"
    ln -sfn "$binary" "$server_link"
    rm -rf "$tmp_dir"
    trap - RETURN
}

write_default_env() {
    if [[ -f "$env_file" ]]; then
        return 0
    fi

    mkdir -p "$config_dir"
    cat > "$env_file" <<'EOF'
LLAMA_CPP_HOST=127.0.0.1
LLAMA_CPP_PORT=8080
LLAMA_CPP_CONTEXT=32768
LLAMA_CPP_BATCH=512
LLAMA_CPP_UBATCH=512
LLAMA_CPP_GPU_LAYERS=999
LLAMA_CPP_MODEL=
LLAMA_CPP_MODEL_ID=local-model
LLAMA_CPP_EXTRA_ARGS="--jinja --flash-attn auto"
EOF
}

write_start_script() {
    mkdir -p "$bin_dir"
    cat > "$start_script" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

env_file="$HOME/.config/llama.cpp/server.env"

if [[ -f "$env_file" ]]; then
    # This file is generated by dotfiles model scripts and contains simple KEY=value pairs.
    source "$env_file"
fi

: "${LLAMA_CPP_HOST:=127.0.0.1}"
: "${LLAMA_CPP_PORT:=8080}"
: "${LLAMA_CPP_CONTEXT:=32768}"
: "${LLAMA_CPP_BATCH:=512}"
: "${LLAMA_CPP_UBATCH:=512}"
: "${LLAMA_CPP_GPU_LAYERS:=999}"
: "${LLAMA_CPP_MODEL_ID:=local-model}"

if [[ -z "${LLAMA_CPP_MODEL:-}" ]]; then
    echo "[ERROR] LLAMA_CPP_MODEL is not set in $env_file" >&2
    exit 1
fi

if [[ ! -f "$LLAMA_CPP_MODEL" ]]; then
    echo "[ERROR] Model file not found: $LLAMA_CPP_MODEL" >&2
    exit 1
fi

exec "$HOME/.local/bin/llama-server" \
    --model "$LLAMA_CPP_MODEL" \
    --alias "$LLAMA_CPP_MODEL_ID" \
    --host "$LLAMA_CPP_HOST" \
    --port "$LLAMA_CPP_PORT" \
    --ctx-size "$LLAMA_CPP_CONTEXT" \
    --batch-size "$LLAMA_CPP_BATCH" \
    --ubatch-size "$LLAMA_CPP_UBATCH" \
    --n-gpu-layers "$LLAMA_CPP_GPU_LAYERS" \
    ${LLAMA_CPP_EXTRA_ARGS:-}
EOF
    chmod +x "$start_script"
}

env_has_model() {
    local model=""

    [[ -f "$env_file" ]] || return 1
    model="$(grep -E '^LLAMA_CPP_MODEL=' "$env_file" | tail -n 1 | cut -d= -f2- || true)"
    model="${model%\"}"
    model="${model#\"}"
    [[ -n "$model" && -f "$model" ]]
}

ensure_service_file() {
    if [[ ! -f "$service_source" ]]; then
        echo "[ERROR] Missing service file in dotfiles repo: $service_source"
        exit 1
    fi

    if [[ -e "$service_target" && ! -L "$service_target" ]]; then
        echo "[ERROR] Refusing to replace non-symlink service file: $service_target"
        exit 1
    fi

    mkdir -p "$(dirname "$service_target")"
    ln -sfn "$service_source" "$service_target"
}

case "$command" in
    apply)
        if ! missing_commands; then
            echo "[ERROR] Install missing runtime tools before applying llama.cpp."
            exit 1
        fi

        mkdir -p "$bin_dir" "$config_dir" "$models_dir"
        install_release_binary
        write_default_env
        write_start_script
        ensure_service_file

        systemctl --user daemon-reload
        if env_has_model; then
            echo "[INFO] Enabling $service."
            systemctl --user enable --now "$service"
        else
            echo "[INFO] llama.cpp installed. Select a llama-model-* script to enable a model."
        fi
        ;;
    purge)
        echo "[INFO] Disabling $service."
        systemctl --user disable --now "$service" || true
        rm -f "$server_link" "$start_script"
        rm -rf "$runtime_dir"
        echo "[INFO] Kept llama.cpp models and config under $models_dir and $config_dir."
        ;;
    dry-run)
        if [[ -x "$server_link" ]]; then
            echo "[DRY-RUN] llama-server is installed: $server_link"
        else
            echo "[DRY-RUN] Would download latest llama.cpp Linux Vulkan release binary."
        fi
        echo "[DRY-RUN] Would install launcher: $start_script"
        echo "[DRY-RUN] Would create default env if missing: $env_file"
        echo "[DRY-RUN] Would enable $service only when a model is configured."
        ;;
    status)
        if [[ -x "$server_link" ]]; then
            echo "[OK] llama-server installed: $server_link"
        else
            echo "[MISSING] llama-server is not installed"
        fi

        if [[ -f "$env_file" ]]; then
            echo "[OK] llama.cpp env: $env_file"
        else
            echo "[MISSING] llama.cpp env: $env_file"
        fi

        echo "[INFO] systemd user service status: $service"
        systemctl --user is-enabled "$service" || true
        systemctl --user is-active "$service" || true
        ;;
    *)
        echo "Usage: $0 [apply|purge|dry-run|status]"
        exit 1
        ;;
esac
